//Do not edit! This file was generated by Unity-ROS MessageGeneration.
using System;
using System.Linq;
using System.Collections.Generic;
using System.Text;
using Unity.Robotics.ROSTCPConnector.MessageGeneration;

namespace RosMessageTypes.Mrirac
{
    [Serializable]
    public class SwitchControllerResponse : Message
    {
        public const string k_RosMessageName = "mrirac_msgs/SwitchController";
        public override string RosMessageName => k_RosMessageName;

        public bool ok;

        public SwitchControllerResponse()
        {
            this.ok = false;
        }

        public SwitchControllerResponse(bool ok)
        {
            this.ok = ok;
        }

        public static SwitchControllerResponse Deserialize(MessageDeserializer deserializer) => new SwitchControllerResponse(deserializer);

        private SwitchControllerResponse(MessageDeserializer deserializer)
        {
            deserializer.Read(out this.ok);
        }

        public override void SerializeTo(MessageSerializer serializer)
        {
            serializer.Write(this.ok);
        }

        public override string ToString()
        {
            return "SwitchControllerResponse: " +
            "\nok: " + ok.ToString();
        }

#if UNITY_EDITOR
        [UnityEditor.InitializeOnLoadMethod]
#else
        [UnityEngine.RuntimeInitializeOnLoadMethod]
#endif
        public static void Register()
        {
            MessageRegistry.Register(k_RosMessageName, Deserialize, MessageSubtopic.Response);
        }
    }
}
